### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rastus-vernon** [roelvandijk/base-unicode-symbols#10]
I have found in Data.List.Unicode some symbols that are not exact synonyms for existing functions (∆, ∌, ∋), so I thought it is fine to suggest some new symbols that are also not synonyms for existing functions. I think the three symbols that follow should be placed in Data.Bool.Unicode, and the two next in Prelude.Unicode (because that's where `mod` is located).

exclusive disjunction
U+22BB: XOR
`a ⊻ b = (a || b) && not (a && b)`

alternative denial
U+22BC: NAND
`(⊼) = not . (&&)`

joint denial
U+22BD: NOR
`(⊽) = not . (||)`

U+2223: DIVIDES
`a ∣ b = mod a b == 0`

U+2224: DOES NOT DIVIDE
`a ∤ b = not . (∣)`

I would also suggest adding the following, in Prelude.Unicode because that's where `sqrt` is.

square root
U+221A: SQUARE ROOT
`(√) = sqrt`

Finally, I found the following silly cases that I am presenting here for enjoyment:
#### Prelude.Unicode

U+26A0: WARNING SIGN
`(⚠) = error`
#### Data.Eq.Unicode

U+22DA: LESS-THAN EQUAL TO OR GREATER-THAN
`(⋚) = (==)`

U+22DB: GREATER-THAN EQUAL TO OR LESS-THAN
`(⋛) = (==)`

U+2A75: TWO CONSECUTIVE EQUALS SIGNS
`(⩵) = (==)`
#### Data.List

U+22BA: INTERCALATE
`(⊺) = intercalate`

**Comment by roelvandijk** [comment]
I'm closing this issue. Most symbols where added.
