### ISSUE TITLE
Unicode double-struck for Natural?

### ISSUE THREAD

**Issue by subttle** [roelvandijk/base-unicode-symbols#18]
Hi, thank you again for your project! Currently there is `type ℤ = Integer` but no `type ℕ = Natural` for the `Natural` type which is in base (since 4.8.0.0) under `Numeric.Natural`. If you are open to the idea I can submit a pull request. Thank you for your consideration.

**Comment by roelvandijk** [comment]
Implemented in f9b8632aa6b9bb9d2197c4682f10106f1e9b2175
